#!/usr/bin/env bash
# display 4 and then bad luck from china
# display 9 then bad luck from Japan
# display 17 and then bad luck from Italy
i=0
while (( i <= 19 ))
do
echo "$i"
case $i
4) echo "bad luck from China";;
9) echo "bad luck from Japan";;
17) echo "bad luck from Italy";;
;;
   esac
   done
