#!/usr/bin/env bash
# Bash script that displays:
# To infinity and beyond indefinitely with sleep 2 between iteration, I am invicible!!! when receiving SIGTERM

trap "I am invincible!!!" SIGTERM

while true
do
echo "To infinity and beyond"
sleep 2
done
